name: FIXME: Your name here
description: FIXME: Provide a description here
author: FIXME: Your name or organization here
inputs:
  FIXME:
  myInput:
    description: input description here
    default: default value if applicable
runs:
  using: node12
  main: dist/index.js
