name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm ci

    - run: npm run build

    - name: Prettier
      uses: harveyr/gh-action-prettier@releases/v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        patterns: src/**.ts

    - name: ESLint
      run: npx eslint src/**/**.ts __tests__/**/**.ts

    - run: npm test

    # zeit is a documented alternative to publishing node_modules:
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action
    - run: npm run dist

    - uses: ./
