name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm ci

    - run: npm run dist

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install mypy
      run: pip install mypy

    - uses: ./
      with:
        patterns: __tests__/assets/
      env:
        ACTIONS_STEP_DEBUG: 'true'

    - run: npx prettier --list-different src/**/**.ts

    - run: npx eslint src/**/**.ts __tests__/**/**.ts

    - run: npm run build

    - run: npm test

    - uses: harveyr/gh-action-publish@releases/v0
      with:
        dirs: dist
      if: contains(github.ref, 'refs/heads/versions/' )
